dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake gcc-8 can-utils g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
  - sudo apt-get install build-essential linux-headers-$(uname -r) cmake

language: c++

compiler:
  - gcc


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
